repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-private-key
    - id: requirements-txt-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff
        args: [check, --select, I, --fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    - id: mypy
      args: [--ignore-missing-imports]
  - repo: https://github.com/djlint/djlint
    rev: v1.34.1
    hooks:
    - id: djlint-reformat-jinja
      args: [static/templates, --format-attribute-template-tags, --quiet]
    - id: djlint-jinja
      args: [static/templates, --ignore=H008, --quiet]
  - repo: local
    hooks:
     - id: requirements
       name: requirements
       entry: bash -c '.venv/bin/pip3 freeze > requirements.txt; git add requirements.txt'
       language: system
       pass_filenames: false
       stages: [commit]
